# sidebar
title: Enthusiastic Lake Gremlin
author:
  name   : "Hannah Weller"
  avatar : "/assets/images/WellerH_profile_photo_SICB2019.JPG"
  bio    : " Graduate student, ginger nut, aquatic lunatic, etc"
  location: "Brown University, Providence, RI"
  links:
    - label: "Website"
      icon: "fas fa-fish"
      url: "https://hiweller.github.io"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/hannahiweller"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/hiweller"
    - label: "Email"
      icon: "fas fa-envelope"

# footer
footer:
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/hannahiweller"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/hiweller"


email: hannahiweller@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Graduate student, ginger nut, aquatic lunatic, etc
twitter_username: hannahiweller
github_username: hiweller
minimal_mistakes_skin: dark
search: true

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes

# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
locale: "en-US"
include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache


teaser: /assets/images/holy-worm.jpg
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: false
      share: true
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
